[build]
  publish = "." # Le dossier où se trouve votre site HTML
  functions = "functions" # Dossier où sont stockées vos fonctions Netlify (comme generateMenus.js)

[functions]
  node_bundler = "esbuild" # Option pour spécifier comment les fonctions sont gérées par Netlify
